### ISSUE TITLE
Adding C++17 support with #include <functional> for io/chunk_and_pool.h

### ISSUE THREAD

**Issue by jelkose** [dspeterson/dory#16]
To get dory compiling with c++17 

`#include <functional>`

should be added to [/dspeterson/dory/blob/master/src/io/chunk_and_pool.h](dspeterson/dory/blob/master/src/io/chunk_and_pool.h)

**Comment by dspeterson** [comment]
Ok, thanks!  I'll add this to my list of things to fix this weekend.  Keep the problem reports coming...

**Comment by dspeterson** [comment]
fixed in version 2.1.3
