### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CogumelosMaravilha** [dspeterson/dory#7]
After "Setting Up a Ubuntu Build Environment (16.04 LTS, 15.04 LTS, 14.04.1 LTS, and 13.10)" we expected a Debian based install. But following the link is a Red Hat based install.

**Comment by dspeterson** [comment]
If you're on the page entitled "Setting Up a Ubuntu Build Environment (16.04 LTS, 15.04 LTS, 14.04.1 LTS, and 13.10)", and you click the link where it says "Now proceed to build, install, and configure Dory.", this takes you to the page entitled "Building and Installing Dory", which tells you to clone Dory's Git repo and then has a subsection entitled "Building an RPM package".  Is this what you are referring to?

If so, I can see how that would be confusing to a Debian/Ubuntu user.  Maybe I should change the subsection title to something like "Building an RPM package (CentOS/RHEL users only)".  Unfortunately I don't yet have a Debian package for Dory.  Even though the RPM-specific steps don't apply, you should still be able to follow the other steps for building/installing manually without RPM.  Hopefully I will get around to making a Debian package some time in the not too distant future.  Or if you want to contribute a debian package, your contribution would be very welcome :-)

Let me know if you run into any other problems, or places where the documentation can be improved.

**Comment by dspeterson** [comment]
I just edited the documentation.  Hopefully it is less confusing now.
