### ISSUE TITLE
readdir_r is deprecated

### ISSUE THREAD

**Issue by CogumelosMaravilha** [dspeterson/dory#8]
In my system I needed to tweak SConstruct in # Environment:

# Environment.
env = Environment(CFLAGS=['-Wwrite-strings'],
    CCFLAGS=['-Wall', '-Wextra', '-Wno-error=deprecated-declarations', '-Wformat=2',

Basically since there are deprecated functions I needed to add '-Wno-error=deprecated-declarations' to work around this error: readdir_r is deprecated.

**Comment by dspeterson** [comment]
What distro are you building on, and what line of code is the warning coming from?  Ideally, I would like to fix the code if possible, or wrap the offending line of code with a #pragma to silence the warning just at the location where it's occurring.

**Comment by CogumelosMaravilha** [comment]
Already on Ubuntu 17.04. Yes 17.04 not 16.04.

**Comment by dspeterson** [comment]
Ok, I'll try building on Ubuntu 17, and implement a fix.

**Comment by dspeterson** [comment]
I implemented fixes for problems encountered while building on Ubuntu 17.  The latest release should work without problems on that platform.  Let me know if you run into any more issues.
